/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSuppliersRouteImport } from './routes/_app/suppliers'
import { Route as AppStockMovementRouteImport } from './routes/_app/stock-movement'
import { Route as AppItemsRouteImport } from './routes/_app/items'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCategoriesRouteImport } from './routes/_app/categories'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppStockMovementRoute = AppStockMovementRouteImport.update({
  id: '/stock-movement',
  path: '/stock-movement',
  getParentRoute: () => AppRoute,
} as any)
const AppItemsRoute = AppItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/categories': typeof AppCategoriesRoute
  '/dashboard': typeof AppDashboardRoute
  '/items': typeof AppItemsRoute
  '/stock-movement': typeof AppStockMovementRoute
  '/suppliers': typeof AppSuppliersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/categories': typeof AppCategoriesRoute
  '/dashboard': typeof AppDashboardRoute
  '/items': typeof AppItemsRoute
  '/stock-movement': typeof AppStockMovementRoute
  '/suppliers': typeof AppSuppliersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/items': typeof AppItemsRoute
  '/_app/stock-movement': typeof AppStockMovementRoute
  '/_app/suppliers': typeof AppSuppliersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/categories'
    | '/dashboard'
    | '/items'
    | '/stock-movement'
    | '/suppliers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/categories'
    | '/dashboard'
    | '/items'
    | '/stock-movement'
    | '/suppliers'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/categories'
    | '/_app/dashboard'
    | '/_app/items'
    | '/_app/stock-movement'
    | '/_app/suppliers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/suppliers': {
      id: '/_app/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock-movement': {
      id: '/_app/stock-movement'
      path: '/stock-movement'
      fullPath: '/stock-movement'
      preLoaderRoute: typeof AppStockMovementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/items': {
      id: '/_app/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof AppItemsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppItemsRoute: typeof AppItemsRoute
  AppStockMovementRoute: typeof AppStockMovementRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCategoriesRoute: AppCategoriesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppItemsRoute: AppItemsRoute,
  AppStockMovementRoute: AppStockMovementRoute,
  AppSuppliersRoute: AppSuppliersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
